# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Microsoft.VisualStudio.2010.ToolsOfficeRuntime
PackageVersion: '10.0.60828'
PackageLocale: en-US
Publisher: Microsoft Corporation
PublisherUrl: https://www.microsoft.com
PackageName: Visual Studio 2010 Tools for Office Runtime
PackageUrl: https://learn.microsoft.com/visualstudio/vsto/visual-studio-tools-for-office-runtime-overview
License: Proprietary
Copyright: Copyright (c) Microsoft Corporation
ShortDescription: Visual Studio 2010 Tools for Office Runtime is required to run Microsoft Office based solutions built using Microsoft Visual Studio 2010, 2012, 2013 and 2015.
ReleaseNotesUrl: https://www.microsoft.com/download/details.aspx?id=56961
ManifestType: defaultLocale
ManifestVersion: 1.4.0
