# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: Microsoft.VisualStudio.2010.ToolsOfficeRuntime
PackageVersion: '10.0.60828.00'
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.4.0
