# Created with Komac v1.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.VisualStudio.2010.ToolsOfficeRuntime
PackageVersion: '10.0.60833'
InstallerLocale: en-US
InstallerType: exe
InstallerSwitches:
  Silent: /q
  SilentWithProgress: /q
  Custom: /norestart
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://download.microsoft.com/download/C/A/8/CA86DFA0-81F3-4568-875A-7E7A598D4C1C/vstor_redist.exe
  InstallerSha256: 2B656781C884647A5368DADB0A4D63488413EA59A86D73E1802308D526B2BF84
ManifestType: installer
ManifestVersion: 1.4.0
